# Generated by Django 5.0.3 on 2024-03-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_oder_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='long',
        ),
    ]
