# Generated by Django 5.0.3 on 2024-03-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product_alter_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
    ]
