# Generated by Django 5.0.3 on 2024-03-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address_name', models.CharField(max_length=200)),
                ('work_time', models.TimeField()),
                ('phone_number', models.CharField(max_length=13)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
    ]
