# Generated by Django 5.0.3 on 2024-03-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='work_time',
            field=models.CharField(max_length=200),
        ),
    ]
